/**
 * Quick Start spec builder (PI-TTFV Iter 1).
 *
 * Product purpose (locked):
 *   This is the inverted entry door. Instead of hand-authoring a structured
 *   WorkflowSpec field-by-field (the Build tab), the user types a single
 *   natural-language request OR pastes a plan generated by Claude / Cursor /
 *   Copilot. We turn that text into the SAME WorkflowSpec contract the rest of
 *   the system already consumes, then route into the existing intake ->
 *   understanding -> reviewing -> ApprovalFrame chain.
 *
 *   It is a text-to-spec adapter, not an interpreter:
 *     - It does NOT parse intent (intake owns that).
 *     - It does NOT preview execution semantics.
 *     - It does NOT decide runtime authority.
 *   Every task still passes through the deterministic parser and the approval
 *   gate. This helper only removes authoring friction before that point.
 *
 *   Default runtime is "cursor" (local file edits) because that path needs no
 *   external API key, so a first-time user can reach the ApprovalFrame value
 *   moment without hitting the credential wall.
 */

import type { WorkflowSpec, WorkflowTaskSpec } from "../api/types.js";

/** Leading list markers we strip so pasted plans become clean task inputs. */
const LIST_MARKER = /^\s*(?:[-*•]|\d+[.)])\s+/;

/**
 * Split raw text into one task input per non-empty line, stripping leading
 * list markers ("1. ", "- ", "* ", "• "). A single-line request yields one
 * task; a pasted numbered/bulleted plan yields one task per step.
 */
export function splitQuickStartTasks(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.replace(LIST_MARKER, "").trim())
    .filter((line) => line.length > 0);
}

/**
 * Derive a short, human-readable workflow name from the first meaningful line.
 * Falls back to "Quick workflow" for whitespace-only input. Capped so the
 * history/review surfaces stay readable.
 */
export function deriveQuickStartName(text: string): string {
  const firstLine =
    text
      .split(/\r?\n/)
      .map((line) => line.replace(LIST_MARKER, "").trim())
      .find((line) => line.length > 0) ?? "";

  if (firstLine.length === 0) return "Quick workflow";

  const words = firstLine.split(/\s+/).slice(0, 8).join(" ");
  const capped = words.length > 60 ? words.slice(0, 60).trim() : words;
  return capped.length > 0 ? capped : "Quick workflow";
}

/**
 * Build a minimal WorkflowSpec from free text. Returns null when there is no
 * actionable content (so callers can keep the Continue button disabled).
 *
 * @param text     natural-language request or pasted AI plan
 * @param runtime  task runtime; defaults to "cursor" (no API key required)
 */
export function buildQuickStartSpec(
  text: string,
  runtime: "cursor" | "claude" = "cursor",
): WorkflowSpec | null {
  const inputs = splitQuickStartTasks(text);
  if (inputs.length === 0) return null;

  const tasks: WorkflowTaskSpec[] = inputs.map((input) => ({ input, runtime }));
  return { name: deriveQuickStartName(text), tasks };
}
